### ISSUE TITLE
Have SSL issue with My Link 

### ISSUE THREAD

**Issue by kukkalu** [Clinton-Abraham/UPLOADER-BOT#42]
![Screenshot_2022-08-10-00-34-22-310_org telegram messenger](https://user-images.githubusercontent.com/61946705/184495761-6e0c442e-f0b1-497f-99f0-ea9fbaae5959.jpg)
 How to fix this Error... Please reply

**Comment by Clinton-Abraham** [comment]
> ![Screenshot_2022-08-10-00-34-22-310_org telegram messenger](https://user-images.githubusercontent.com/61946705/184495761-6e0c442e-f0b1-497f-99f0-ea9fbaae5959.jpg) How to fix this Error... Please reply

Contact repo developer bro.. it's not mine  :(

**Comment by kukkalu** [comment]
Brother i tried your also it also same brother once contact me on telegram i will explain @niranjantech

**Comment by Clinton-Abraham** [comment]
Then contact site owner Bro.. i can't do anything

**Comment by Clinton-Abraham** [comment]
Url uploader bots only supports direct links

**Comment by kukkalu** [comment]
Brother i saw 1 tg bot it supportted my link... But it was have delay time for every use... So iam asking fix that issue in your bot give support
