### ISSUE TITLE
Url Bot Error Fix

### ISSUE THREAD

**Issue by kukkalu** [Clinton-Abraham/UPLOADER-BOT#43]
![Screenshot_2022-08-13-18-55-55-047_org telegram messenger](https://user-images.githubusercontent.com/61946705/184496199-66cbc4eb-17e5-48c8-996b-a35d86990d1a.jpg)

Check brother i need fix this issue i am trying from many days

**Comment by Clinton-Abraham** [comment]
Already told you bro... Bot only supports direct link

**Comment by kukkalu** [comment]
But already one bot on telegram is support this link
