### ISSUE TITLE
Deploy on VPS

### ISSUE THREAD

**Issue by iMazXZ** [Clinton-Abraham/UPLOADER-BOT#50]
It can be deploy on VPS?

**Comment by tom-snow** [comment]
```
git clone https://github.com/Clinton-Abraham/UPLOADER-BOT.git
cd UPLOADER-BOT
pip install -r requirements.txt
# edit config.py
python bot.py
```

**Comment by Clinton-Abraham** [comment]
@tom-snow ❤️

**Comment by arjung24** [comment]
> @tom-snow ❤️

![IMG_20230527_151834](https://github.com/Clinton-Abraham/UPLOADER-BOT/assets/68998000/90db45d6-3798-4bb5-8443-923a6b2f4830)

Please help

**Comment by tom-snow** [comment]
https://github.com/Clinton-Abraham/UPLOADER-BOT/blob/085f81a3bd320bc5436607bc19d89132c50b3e79/config.py#L7

edit config file first

**Comment by arjung24** [comment]
> https://github.com/Clinton-Abraham/UPLOADER-BOT/blob/085f81a3bd320bc5436607bc19d89132c50b3e79/config.py#L7
> 
> edit config file first

I did

**Comment by arjung24** [comment]
> https://github.com/Clinton-Abraham/UPLOADER-BOT/blob/085f81a3bd320bc5436607bc19d89132c50b3e79/config.py#L7
> 
> edit config file first

![IMG_20230527_162140](https://github.com/Clinton-Abraham/UPLOADER-BOT/assets/68998000/02ad1279-1852-46f7-822f-aede39d4313a)
I did

**Comment by arjung24** [comment]
![IMG_20230527_162316](https://github.com/Clinton-Abraham/UPLOADER-BOT/assets/68998000/5818e7c0-2d8a-4ac7-96ba-989370b689ea)

**Comment by Clinton-Abraham** [comment]
> ![IMG_20230527_162316](https://user-images.githubusercontent.com/68998000/241381208-5818e7c0-2d8a-4ac7-96ba-989370b689ea.jpg)

Learn python first 🤬

**Comment by arjung24** [comment]
> > ![IMG_20230527_162316](https://user-images.githubusercontent.com/68998000/241381208-5818e7c0-2d8a-4ac7-96ba-989370b689ea.jpg)
> 
> Learn python first 🤬

Don't hate me Brother. Please help. Not everyone knows everything. That's where u help right?
Please help

**Comment by Clinton-Abraham** [comment]
> > > ![IMG_20230527_162316](https://user-images.githubusercontent.com/68998000/241381208-5818e7c0-2d8a-4ac7-96ba-989370b689ea.jpg)
> > 
> > 
> > Learn python first cursing_face
> 
> Don't hate me Brother. Please help. Not everyone knows everything. That's where u help right? Please help
Ask https://telegram.dog/sources_codes
