### ISSUE TITLE
Use https://t.me/XTZ_HerokuBot to deploy

### ISSUE THREAD

**Issue by RameshBabu45** [Clinton-Abraham/UPLOADER-BOT#66]
Use https://t.me/XTZ_HerokuBot to deploy

_Originally posted by @Clinton-Abraham in https://github.com/Clinton-Abraham/UPLOADER-BOT/issues/14#issuecomment-1021253536_
            

Bot Not Working

**Comment by Clinton-Abraham** [comment]
New version soon with latest pyrofork support 🦊
